version: 2

sources:
  - name: olist
    database: dbt-estudos-501200
    schema: raw
    tables:
      - name: olist_orders

  - name: exemplo
    database: dbt-estudos-501200
    schema: raw
    tables:
      - name: pedidos
      - name: clientes